language: python
python:
- '3.4'
install:
- pip install -r requirements/dev.txt --allow-external thingstance
- pip install python-coveralls
services:
- mongodb
script:
- source ./environment.sh
after_success:
- coveralls --ignore-errors
notifications:
  webhooks:
    urls:
    - https://deployer-openregister.herokuapp.com/deploy-register/field
    - https://deployer-openregister.herokuapp.com/deploy-register/datatype
    - https://deployer-openregister.herokuapp.com/deploy-register/country
    on_failure: never
