language: python
python:
 - '3.4'
install:
 - pip install -r requirements/dev.txt --allow-external thingstance
 - pip install python-coveralls
services:
 - mongodb
script:
 - source ./environment.sh
 - make flake8
 - make test
 - make coveralls
after_success:
 - coveralls --ignore-errors
deploy:
 - provider: heroku
   api_key:
     secure: eSYw1flDzVAq0gpbEaIXJY6ZdgLQIA8FflZFpbVddut5fKPXTi+j7td7gNIf/wo1uPB6uCrhvG1cxLYhuz9N3E6M2m4x5qXIAbdsDZ4sY2paABdQGY0cwmTAkdmb5NSYKzPj4YfBYp7oodjVknwbgSI4+ri8hg36wNQklclfic4=
   app: country-openregister
   on:
     repo: openregister/server
 - provider: heroku
   api_key:
     secure: eSYw1flDzVAq0gpbEaIXJY6ZdgLQIA8FflZFpbVddut5fKPXTi+j7td7gNIf/wo1uPB6uCrhvG1cxLYhuz9N3E6M2m4x5qXIAbdsDZ4sY2paABdQGY0cwmTAkdmb5NSYKzPj4YfBYp7oodjVknwbgSI4+ri8hg36wNQklclfic4=
   app: field-openregister
   on:
     repo: openregister/server
 - provider: heroku
   api_key:
     secure: eSYw1flDzVAq0gpbEaIXJY6ZdgLQIA8FflZFpbVddut5fKPXTi+j7td7gNIf/wo1uPB6uCrhvG1cxLYhuz9N3E6M2m4x5qXIAbdsDZ4sY2paABdQGY0cwmTAkdmb5NSYKzPj4YfBYp7oodjVknwbgSI4+ri8hg36wNQklclfic4=
   app: register-openregister
   on:
     repo: openregister/server